/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e0e3e5',
        'glass-border': 'rgba(255, 255, 255, 0.4)',
        'surface-bright': '#f7fafc',
        'surface-container-low': '#f1f4f6',
        error: '#ba1a1a',
        'tertiary-container': '#572900',
        'on-secondary-container': '#00723f',
        'vibrant-green': '#48BB78',
        'on-primary-fixed-variant': '#2d476f',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        surface: '#f7fafc',
        'primary-container': '#1a365d',
        'inverse-on-surface': '#eef1f3',
        'on-tertiary-fixed-variant': '#703700',
        'on-tertiary': '#ffffff',
        primary: '#002045',
        'on-surface': '#181c1e',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#301400',
        'surface-dim': '#d7dadc',
        'primary-fixed': '#d6e3ff',
        outline: '#74777f',
        tertiary: '#371800',
        'on-tertiary-container': '#e88532',
        'on-primary-fixed': '#001b3c',
        'surface-container': '#ebeef0',
        'primary-fixed-dim': '#adc7f7',
        'secondary-fixed-dim': '#6bdc96',
        'inverse-surface': '#2d3133',
        'outline-variant': '#c4c6cf',
        'deep-navy': '#1A365D',
        'on-surface-variant': '#43474e',
        'energetic-orange': '#ED8936',
        'secondary-fixed': '#88f9b0',
        'on-secondary-fixed-variant': '#00522c',
        'inverse-primary': '#adc7f7',
        'tertiary-fixed-dim': '#ffb783',
        'on-primary-container': '#86a0cd',
        background: '#f7fafc',
        'error-container': '#ffdad6',
        secondary: '#006d3c',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#00210f',
        'surface-container-high': '#e5e9eb',
        'glass-surface': 'rgba(255, 255, 255, 0.7)',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ffdcc5',
        'on-background': '#181c1e',
        'on-secondary': '#ffffff',
        'secondary-container': '#85f6ad',
        'surface-tint': '#455f88',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'margin-mobile': '20px',
        'stack-lg': '32px',
        'section-gap': '120px',
        gutter: '24px',
      },
      fontFamily: {
        'display-lg-mobile': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'headline-sm': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
